vich_uploader:
    db_driver: orm

    mappings:
        blog_images:
            uri_prefix:         '/images/Images'
            upload_destination: '%kernel.project_dir%/public/images/Images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
